name: metadata_fetch
description: A library for fetching metadata from websites
version: 0.1.0
homepage: https://www.example.com

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  path: ^1.6.0
  http: ^0.12.0+4
  string_validator: ^0.1.3
  html: ^0.14.0+3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
